export const LEAD_STATUS = {
  NEW: 'new',
  QUALIFIED: 'qualified',
  UNQUALIFIED: 'unqualified',
  QUOTATION_SHARED: 'quotation_shared',
  INTERESTED: 'interested',
  NEGOTIATION: 'negotiation',
  LOST: 'lost',
  CONVERTED: 'converted',
} as const

export type LeadStatus = typeof LEAD_STATUS[keyof typeof LEAD_STATUS]

export const LEAD_STATUS_LABELS: Record<LeadStatus, string> = {
  [LEAD_STATUS.NEW]: 'New Lead',
  [LEAD_STATUS.QUALIFIED]: 'Qualified',
  [LEAD_STATUS.UNQUALIFIED]: 'Unqualified',
  [LEAD_STATUS.QUOTATION_SHARED]: 'Quotation Shared',
  [LEAD_STATUS.INTERESTED]: 'Interested',
  [LEAD_STATUS.NEGOTIATION]: 'Negotiation',
  [LEAD_STATUS.LOST]: 'Lost',
  [LEAD_STATUS.CONVERTED]: 'Converted',
}

export const LEAD_STATUS_FLOW: Record<LeadStatus, LeadStatus[]> = {
  [LEAD_STATUS.NEW]: [LEAD_STATUS.QUALIFIED, LEAD_STATUS.UNQUALIFIED],
  [LEAD_STATUS.QUALIFIED]: [LEAD_STATUS.QUOTATION_SHARED],
  [LEAD_STATUS.UNQUALIFIED]: [LEAD_STATUS.NEW],
  [LEAD_STATUS.QUOTATION_SHARED]: [LEAD_STATUS.INTERESTED, LEAD_STATUS.NEGOTIATION, LEAD_STATUS.LOST],
  [LEAD_STATUS.INTERESTED]: [LEAD_STATUS.NEGOTIATION, LEAD_STATUS.CONVERTED, LEAD_STATUS.LOST],
  [LEAD_STATUS.NEGOTIATION]: [LEAD_STATUS.CONVERTED, LEAD_STATUS.LOST],
  [LEAD_STATUS.LOST]: [],
  [LEAD_STATUS.CONVERTED]: [],
}
